services:
#    review.example:
#        class: ReviewBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    user.data.fetcher:
      class : ReviewBundle\Services\DataFetcherService

    import.csv2array:
      class : ReviewBundle\Services\Csv2ArrayService